local Translations = {
    error = {
        testdrive_alreadyin = "Trwa jazda próbna",
        testdrive_return = "To nie jest Twój pojazd do jazdy próbnej",
        Invalid_ID = "Invalid Player Id Supplied",
        playertoofar = "Ten gracz nie jest wystarczająco blisko",
        notenoughmoney = "Niewystarczająca ilość pieniędzy",
        minimumallowed = "Minimalna dozwolona płatność to $",
        overpaid = "Przepłaciłeś",
        alreadypaid = "Samochód jest już opłacony",
        notworth = "Pojazd nie jest tyle wart",
        downtoosmall = "Zaliczka za mała",
        exceededmax = "Przekroczono maksymalną kwotę płatności",
        repossessed = "Twój pojazd z tablicą rejestracyjną %{plate} został przejęty",
        buyerinfo = "Nie udało się uzyskać informacji o kupującym",
        notinveh = "Musisz znajdować się w pojeździe, który chcesz przenieść",
        vehinfo = "Nie udało się uzyskać informacji o pojeździe",
        notown = "Nie jesteś właścicielem tego pojazdu",
        buyertoopoor = "Kupujący nie ma wystarczającej ilości pieniędzy",
        nofinanced = "Nie masz żadnych finansowanych pojazdów",
        financed = "Ten pojazd jest finansowany",
    },
    success = {
        purchased = "Gratulujemy zakupu!",
        earned_commission = "Zarobiłeś $ %{amount} prowizji",
        gifted = "Podarowałeś swój pojazd",
        received_gift = "Dostałeś w prezencie pojazd",
        soldfor = "Sprzedałeś swój pojazd za $",
        boughtfor = "Kupiłeś samochód za $",
    },
    menus = {
        vehHeader_header = "Opcje pojazdu",
        vehHeader_txt = "Wejdź w interakcję z obecnym pojazdem",
        financed_header = "Finansowane pojazdy",
        finance_txt = "Przeglądaj posiadane pojazdy",
        returnTestDrive_header = "Zakończ jazdę próbną",
        goback_header = "Wróć",
        veh_price = "Cena: $",
        veh_platetxt = "Rejestracja: ",
        veh_finance = "Płatność za pojazd",
        veh_finance_balance = "Pozostałe saldo",
        veh_finance_currency = "$",
        veh_finance_total = "Całkowita pozostała płatność",
        veh_finance_reccuring = "Kwota płatności cyklicznej",
        veh_finance_pay = "Dokonaj płatności",
        veh_finance_payoff = "Pojazd do wypłaty",
        veh_finance_payment = "Wielkość płatności ($)",
        submit_text = "Wyślij",
        test_header = "Jazda testowa",
        finance_header = "Finansuj pojazd",
        swap_header = "Zamień pojazd",
        swap_txt = "Zmień aktualnie wybrany pojazd",
        financesubmit_downpayment = "Kwota zaliczki - min",
        financesubmit_totalpayment = "Łączne płatności — maks",
        --Free Use
        freeuse_test_txt = "Jazda próbna aktualnie wybranym pojazdem",
        freeuse_buy_header = "Kup pojazd",
        freeuse_buy_txt = "Kup aktualnie wybrany pojazd",
        freeuse_finance_txt = "Finansuj aktualnie wybrany pojazd",
        --Managed
        managed_test_txt = "Zezwól graczowi na jazdę próbną",
        managed_sell_header = "Sprzedaj pojazd",
        managed_sell_txt = "Sprzedaj pojazd graczowi",
        managed_finance_txt = "Finansuj pojazd dla gracza",
        submit_ID = "Serwer ID (#)",
    },
    general = {
        testdrive_timer = "Pozostały czas jazdy próbnej:",
        vehinteraction = "Interakcja pojazdu",
        testdrive_timenoti = "Pozostało Ci %{testdrivetime} minut",
        testdrive_complete = "Jazda próbna zakończona",
        paymentduein = "Termin płatności za pojazd przypada w ciągu %{time} minut",
        command_transfervehicle = "Podaruj lub sprzedaj swój pojazd",
        command_transfervehicle_help = "ID kupującego",
        command_transfervehicle_amount = "Kwota sprzedaży (opcjonalnie)",
    }
}

if GetConvar('qb_locale', 'en') == 'pl' then
    Lang = Locale:new({
        phrases = Translations,
        warnOnMissing = true,
        fallbackLang = Lang,
    })
end
